--[[
    init.lua
    Created: 01/16/2024 04:13:56
    Description: Autogenerated script file for the map kingofthewott_floor1.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local kingofthewott_floor1 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---kingofthewott_floor1.Init(map)
--Engine callback function
function kingofthewott_floor1.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---kingofthewott_floor1.Enter(map)
--Engine callback function
function kingofthewott_floor1.Enter(map)

  GAME:FadeIn(20)

end

---kingofthewott_floor1.Exit(map)
--Engine callback function
function kingofthewott_floor1.Exit(map)


end

---kingofthewott_floor1.Update(map)
--Engine callback function
function kingofthewott_floor1.Update(map)


end

---kingofthewott_floor1.GameSave(map)
--Engine callback function
function kingofthewott_floor1.GameSave(map)


end

---kingofthewott_floor1.GameLoad(map)
--Engine callback function
function kingofthewott_floor1.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return kingofthewott_floor1

