--[[
    init.lua
    Created: 04/22/2024 18:11:51
    Description: Autogenerated script file for the map td_moomoofrenzy.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_moomoofrenzy = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_moomoofrenzy.Init(zone)
--Engine callback function
function td_moomoofrenzy.Init(zone)


end

---td_moomoofrenzy.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_moomoofrenzy.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_moomoofrenzy.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_moomoofrenzy.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_moomoofrenzy.Rescued(zone, name, mail)
--Engine callback function
function td_moomoofrenzy.Rescued(zone, name, mail)


end

return td_moomoofrenzy

