--[[
    init.lua
    Created: 10/31/2023 03:04:14
    Description: Autogenerated script file for the map overworld_another.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local overworld_another = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---overworld_another.Init(map)
--Engine callback function
function overworld_another.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---overworld_another.Enter(map)
--Engine callback function
function overworld_another.Enter(map)

  GAME:FadeIn(20)

end

---overworld_another.Exit(map)
--Engine callback function
function overworld_another.Exit(map)


end

---overworld_another.Update(map)
--Engine callback function
function overworld_another.Update(map)


end

---overworld_another.GameSave(map)
--Engine callback function
function overworld_another.GameSave(map)


end

---overworld_another.GameLoad(map)
--Engine callback function
function overworld_another.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return overworld_another

