--[[
    init.lua
    Created: 12/12/2022 16:31:08
    Description: Autogenerated script file for the map monster_museum.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local monster_museum = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---CURMAPSCR.Init
--Engine callback function
function monster_museum.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---CURMAPSCR.Enter
--Engine callback function
function monster_museum.Enter(map)

  GAME:FadeIn(20)

end

---CURMAPSCR.Exit
--Engine callback function
function monster_museum.Exit(map)


end

---CURMAPSCR.Update
--Engine callback function
function monster_museum.Update(map)


end

---CURMAPSCR.GameSave
--Engine callback function
function monster_museum.GameSave(map)


end

---CURMAPSCR.GameLoad
--Engine callback function
function monster_museum.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return monster_museum

