--[[
    init.lua
    Created: 01/10/2024 05:53:26
    Description: Autogenerated script file for the map fibertree.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local fibertree = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---fibertree.Init(map)
--Engine callback function
function fibertree.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---fibertree.Enter(map)
--Engine callback function
function fibertree.Enter(map)

  GAME:FadeIn(20)

end

---fibertree.Exit(map)
--Engine callback function
function fibertree.Exit(map)


end

---fibertree.Update(map)
--Engine callback function
function fibertree.Update(map)


end

---fibertree.GameSave(map)
--Engine callback function
function fibertree.GameSave(map)


end

---fibertree.GameLoad(map)
--Engine callback function
function fibertree.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return fibertree

