--[[
    init.lua
    Created: 12/11/2023 19:03:13
    Description: Autogenerated script file for the map starlight_town.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local starlight_town = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---starlight_town.Init(map)
--Engine callback function
function starlight_town.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---starlight_town.Enter(map)
--Engine callback function
function starlight_town.Enter(map)

  GAME:FadeIn(20)

end

---starlight_town.Exit(map)
--Engine callback function
function starlight_town.Exit(map)


end

---starlight_town.Update(map)
--Engine callback function
function starlight_town.Update(map)


end

---starlight_town.GameSave(map)
--Engine callback function
function starlight_town.GameSave(map)


end

---starlight_town.GameLoad(map)
--Engine callback function
function starlight_town.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return starlight_town

