--[[
    init.lua
    Created: 01/14/2024 06:58:19
    Description: Autogenerated script file for the map apramunem_entrance.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local apramunem_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apramunem_entrance.Init(map)
--Engine callback function
function apramunem_entrance.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---apramunem_entrance.Enter(map)
--Engine callback function
function apramunem_entrance.Enter(map)

  if SV.global_quest.StoryProgression == 30 then
    local gapori = CH('Gapori')
	gapori.CollisionDisabled = true
	GAME:CutsceneMode(true)
	COMMONEX.PlayerCutscene()
	local player = CH('PLAYER')
	SV.checkpoint = 
	{
	  Zone    = 'td_apramunem', Segment  = -1,
	  Map  = 0, Entry  = 0
	}
	GROUND:CharSetAnim(player,"Sleep",true)
	GAME:FadeIn(40)
	GAME:WaitFrames(40)
	GROUND:CharEndAnim(player)
	GAME:WaitFrames(40)
	GROUND:CharSetEmote(player, "question", 1)
	SOUND:PlayBattleSE("EVT_Emote_Confused")
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Left, 5, false)
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Right, 5, true)
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Down, 5, false)
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_0']))
	GROUND:CharAnimateTurn(player, Direction.UpRight, 5, true)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_1']))
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_2']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_3']))
	GROUND:MoveToPosition(gapori, 172, 124, false, 1)
	GROUND:Hide("Gapori")
	GROUND:CharAnimateTurn(player, Direction.Down, 1, false)
	GROUND:RefreshPlayer()
	GAME:CutsceneMode(false)
	SV.global_quest.StoryProgression = 31
  else
    GROUND:Hide("Gapori")
	GAME:FadeIn(20)
  end

end

---apramunem_entrance.Exit(map)
--Engine callback function
function apramunem_entrance.Exit(map)


end

---apramunem_entrance.Update(map)
--Engine callback function
function apramunem_entrance.Update(map)


end

---apramunem_entrance.GameSave(map)
--Engine callback function
function apramunem_entrance.GameSave(map)


end

---apramunem_entrance.GameLoad(map)
--Engine callback function
function apramunem_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function apramunem_entrance.Assembly_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker()
  COMMON.ShowTeamAssemblyMenu(obj, COMMON.RespawnAllies)
end

function apramunem_entrance.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end

return apramunem_entrance

