--[[
    init.lua
    Created: 03/18/2024 18:02:04
    Description: Autogenerated script file for the map gromsey.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local gromsey = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---gromsey.Init(map)
--Engine callback function
function gromsey.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---gromsey.Enter(map)
--Engine callback function
function gromsey.Enter(map)

  GAME:FadeIn(20)

end

---gromsey.Exit(map)
--Engine callback function
function gromsey.Exit(map)


end

---gromsey.Update(map)
--Engine callback function
function gromsey.Update(map)


end

---gromsey.GameSave(map)
--Engine callback function
function gromsey.GameSave(map)


end

---gromsey.GameLoad(map)
--Engine callback function
function gromsey.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return gromsey

