--[[
    init.lua
    Created: 01/14/2024 11:00:35
    Description: Autogenerated script file for the map amusement_park_peronshop.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local amusement_park_peronshop = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---amusement_park_peronshop.Init(map)
--Engine callback function
function amusement_park_peronshop.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---amusement_park_peronshop.Enter(map)
--Engine callback function
function amusement_park_peronshop.Enter(map)

  GAME:FadeIn(20)

end

---amusement_park_peronshop.Exit(map)
--Engine callback function
function amusement_park_peronshop.Exit(map)


end

---amusement_park_peronshop.Update(map)
--Engine callback function
function amusement_park_peronshop.Update(map)


end

---amusement_park_peronshop.GameSave(map)
--Engine callback function
function amusement_park_peronshop.GameSave(map)


end

---amusement_park_peronshop.GameLoad(map)
--Engine callback function
function amusement_park_peronshop.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return amusement_park_peronshop

