--[[
    init.lua
    Created: 02/08/2024 19:07:11
    Description: Autogenerated script file for the map event_apramunem_arena.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local event_apramunem_arena = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_apramunem_arena.Init(map)
--Engine callback function
function event_apramunem_arena.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_apramunem_arena.Enter(map)
--Engine callback function
function event_apramunem_arena.Enter(map)

  GAME:FadeIn(20)

end

---event_apramunem_arena.Exit(map)
--Engine callback function
function event_apramunem_arena.Exit(map)


end

---event_apramunem_arena.Update(map)
--Engine callback function
function event_apramunem_arena.Update(map)


end

---event_apramunem_arena.GameSave(map)
--Engine callback function
function event_apramunem_arena.GameSave(map)


end

---event_apramunem_arena.GameLoad(map)
--Engine callback function
function event_apramunem_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return event_apramunem_arena

