--[[
    init.lua
    Created: 04/22/2024 18:13:22
    Description: Autogenerated script file for the map td_flaming_house.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_flaming_house = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_flaming_house.Init(zone)
--Engine callback function
function td_flaming_house.Init(zone)


end

---td_flaming_house.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_flaming_house.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_flaming_house.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_flaming_house.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_flaming_house.Rescued(zone, name, mail)
--Engine callback function
function td_flaming_house.Rescued(zone, name, mail)


end

return td_flaming_house

