--[[
    init.lua
    Created: 01/21/2024 18:13:25
    Description: Autogenerated script file for the map corneria_replica.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local corneria_replica = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---corneria_replica.Init(map)
--Engine callback function
function corneria_replica.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---corneria_replica.Enter(map)
--Engine callback function
function corneria_replica.Enter(map)

  GAME:FadeIn(20)

end

---corneria_replica.Exit(map)
--Engine callback function
function corneria_replica.Exit(map)


end

---corneria_replica.Update(map)
--Engine callback function
function corneria_replica.Update(map)


end

---corneria_replica.GameSave(map)
--Engine callback function
function corneria_replica.GameSave(map)


end

---corneria_replica.GameLoad(map)
--Engine callback function
function corneria_replica.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return corneria_replica

