--[[
    init.lua
    Created: 08/28/2023 11:58:13
    Description: Autogenerated script file for the map td_hauntedzone.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local td_hauntedzone = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_hauntedzone.Init(zone)
--Engine callback function
function td_hauntedzone.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_td_hauntedzone")
end

---td_hauntedzone.EnterSegment
--Engine callback function
function td_hauntedzone.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---td_hauntedzone.ExitSegment
--Engine callback function
function td_hauntedzone.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_td_hauntedzone result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  COMMON.ExitDungeonMissionCheck(zone.ID, segmentID)
  if rescue == true then
    COMMON.EndRescue(zone, result, segmentID)
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    if segmentID == 0 then
	  if SV.sidequest_buneary > 3 then
	    COMMON.EndDungeonDay(result, 'td_throwback_land', -1, 12, 1)
	  elseif SV.sidequest_buneary == 3 then
	    GAME:ContinueDungeon('td_hauntedzone', 1, 0, 0)
	  else
        GAME:EnterGroundMap("event_hauntedzone_boss", "StartPlayer")
	  end
    elseif segmentID == 1 then
	  GAME:EnterGroundMap("event_hauntedzone_boss", "StartPlayer")
	else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end

---td_hauntedzone.Rescued
--Engine callback function
function td_hauntedzone.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return td_hauntedzone

