--[[
    init.lua
    Created: 01/02/2024 10:31:19
    Description: Autogenerated script file for the map troye_palace.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local troye_palace = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---troye_palace.Init(map)
--Engine callback function
function troye_palace.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---troye_palace.Enter(map)
--Engine callback function
function troye_palace.Enter(map)

  GAME:FadeIn(20)

end

---troye_palace.Exit(map)
--Engine callback function
function troye_palace.Exit(map)


end

---troye_palace.Update(map)
--Engine callback function
function troye_palace.Update(map)


end

---troye_palace.GameSave(map)
--Engine callback function
function troye_palace.GameSave(map)


end

---troye_palace.GameLoad(map)
--Engine callback function
function troye_palace.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return troye_palace

