--[[
    init.lua
    Created: 01/07/2024 11:00:22
    Description: Autogenerated script file for the map continue.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local continue = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---continue.Init(map)
--Engine callback function
function continue.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
  COMMON.RespawnAllies()
  SV.wipedout = false

end

---continue.Enter(map)
--Engine callback function
function continue.Enter(map)

  GAME:FadeIn(20)

end

---continue.Exit(map)
--Engine callback function
function continue.Exit(map)


end

---continue.Update(map)
--Engine callback function
function continue.Update(map)


end

---continue.GameSave(map)
--Engine callback function
function continue.GameSave(map)


end

---continue.GameLoad(map)
--Engine callback function
function continue.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function continue.Assembly_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker()
  COMMON.ShowTeamAssemblyMenu(obj, COMMON.RespawnAllies)
end

function continue.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end

function continue.Counselor_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Sad")
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Counselor_0']))
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Counselor_1']))
end

function continue.Teleport_Touch(obj, activator)
  UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Message_0']), false)
  UI:WaitForChoice()
  local num = SV.global_quest.StoryProgression
  local ch = UI:ChoiceResult()
  if ch then
    GAME:FadeOut(false,20)
    if num == 26 then
      GAME:EnterDungeon('td_throwback_land', 3, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, false, false)
    end
  end
end

function continue.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate4_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate5_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate6_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function continue.Teammate7_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return continue

