--[[
    init.lua
    Created: 10/31/2023 03:05:19
    Description: Autogenerated script file for the map fairyworld.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local fairyworld = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---fairyworld.Init(map)
--Engine callback function
function fairyworld.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---fairyworld.Enter(map)
--Engine callback function
function fairyworld.Enter(map)

  GAME:FadeIn(20)

end

---fairyworld.Exit(map)
--Engine callback function
function fairyworld.Exit(map)


end

---fairyworld.Update(map)
--Engine callback function
function fairyworld.Update(map)


end

---fairyworld.GameSave(map)
--Engine callback function
function fairyworld.GameSave(map)


end

---fairyworld.GameLoad(map)
--Engine callback function
function fairyworld.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return fairyworld

