--[[
    init.lua
    Created: 02/21/2024 07:44:04
    Description: Autogenerated script file for the map td_strangeparadise.
]]--
-- Commonly included lua functions and data
require 'nadiyas_dungeon_collection.common'

-- Package name
local td_strangeparadise = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_strangeparadise.Init(zone)
--Engine callback function
function td_strangeparadise.Init(zone)


end

---td_strangeparadise.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_strangeparadise.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_strangeparadise.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_strangeparadise.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_strangeparadise.Rescued(zone, name, mail)
--Engine callback function
function td_strangeparadise.Rescued(zone, name, mail)


end

return td_strangeparadise

