--[[
    init.lua
    Created: 10/30/2023 17:36:08
    Description: Autogenerated script file for the map event_hauntedzone_boss.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local event_hauntedzone_boss = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_hauntedzone_boss.Init(map)
--Engine callback function
function event_hauntedzone_boss.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_hauntedzone_boss.Enter(map)
--Engine callback function
function event_hauntedzone_boss.Enter(map)

  GAME:CutsceneMode(true)
  local buneary = CH("Buneary")
  local player = CH("PLAYER")
  local mis_0 = CH("Mismagius")
  local mis_1 = CH("Misdreavus_1")
  local mis_2 = CH("Misdreavus_2")
  local mis_3 = CH("Misdreavus_3")
  local mis_4 = CH("Misdreavus_4")
  GROUND:CharSetAnim(buneary, "Float", true)
  if SV.sidequest_buneary == 2 then
    GAME:FadeIn(20)
	GROUND:MoveInDirection(player, Direction.Up, 48, false, 1)
	UI:SetSpeaker(buneary)
	UI:SetSpeakerEmotion("Crying")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Buneary_0']))
	UI:SetSpeaker(mis_0)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mismagius_0']))
	UI:SetSpeaker(mis_1)
	UI:SetSpeakerEmotion("Stunned")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Misdreavus_0']))
	UI:SetSpeaker(mis_0)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mismagius_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mismagius_2']))
	GAME:FadeOut(false,20)
	SV.sidequest_buneary = 3
	GAME:ContinueDungeon('td_hauntedzone', 1, 0, 0)
  else
	GROUND:TeleportTo(player, 183, 166, Direction.Up)
	GAME:FadeIn(20)
	UI:SetSpeaker(mis_0)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mismagius_3']))
	local coro1 = TASK:BranchCoroutine(function() event_hauntedzone_boss.Disappear("Mismagius") end)
	local coro2 = TASK:BranchCoroutine(function() event_hauntedzone_boss.Disappear("Misdreavus_1") end)
	local coro3 = TASK:BranchCoroutine(function() event_hauntedzone_boss.Disappear("Misdreavus_2") end)
	local coro4 = TASK:BranchCoroutine(function() event_hauntedzone_boss.Disappear("Misdreavus_3") end)
	local coro5 = TASK:BranchCoroutine(function() event_hauntedzone_boss.Disappear("Misdreavus_4") end)
	GAME:WaitFrames(90)
	TASK:JoinCoroutines({coro1,coro2,coro3,coro4,coro5})
	GROUND:CharWaitAnim(buneary, "Wake")
	GROUND:CharAnimateTurn(buneary, Direction.Down, 4, true)
	GROUND:MoveInDirection(buneary, Direction.Down, 12, false, 2)
	UI:SetSpeaker(buneary)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Buneary_1']))
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Buneary_2']))
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Buneary_3']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Buneary_4']))
	SV.sidequest_buneary = 4
	COMMONEX.PointIncrease(5)
	GAME:FadeOut(false,60)
	COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'td_throwback_land', -1, 12, 1)
  end
  GAME:CutsceneMode(false)

end

---event_hauntedzone_boss.Exit(map)
--Engine callback function
function event_hauntedzone_boss.Exit(map)


end

---event_hauntedzone_boss.Update(map)
--Engine callback function
function event_hauntedzone_boss.Update(map)


end

---event_hauntedzone_boss.GameSave(map)
--Engine callback function
function event_hauntedzone_boss.GameSave(map)


end

---event_hauntedzone_boss.GameLoad(map)
--Engine callback function
function event_hauntedzone_boss.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function event_hauntedzone_boss.Disappear(character)
  COMMONEX.SmoothRemove(character)
end

return event_hauntedzone_boss

